wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.4
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.6.4
      5: 0.10.31
      8:
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 64
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.003
